### ISSUE TITLE
Node labels remain the same on a tenant cluster after KubeVirt VM is migrated to another zone

### ISSUE THREAD

**Issue by JohnnyMastricht** [kubevirt/cloud-provider-kubevirt#225]
Like described in `README` for our set up we use infrastructure cluster that hosts KubeVirt VMs (previously known as UnderKube) and tenant cluster that uses those VMs as kubernetes nodes (OverKube).

Nodes that host UnderKube VMs are located in two different availability zones and labeled accordingly.

Recently we were testing VM migration scenarios and found out that labels (such as zone) on OverKube nodes always remain the same despite VMs were migrated between racks, meaning different zones.

What we expect: labels are being changed dynamically when KubeVirt VMs on an UnderKube cluster are migrated between availability zones and correctly propagated to kubernetes nodes on a tenant cluster.

I can provide more info if needed about migration steps etc

**Comment by mfranczy** [comment]
As I understand it, the VMs after migrating to a new zone or region had their labels updated accordingly, but only the node labels didn't change, right?

**Comment by JohnnyMastricht** [comment]
@mfranczy Hello, thank you for the reply. 
Unfortunately the original set up was deleted, but from what I recall the VMI intance labels (like `nodeName=`) weren't updated as well as OverKube nodes. The value just remained the same like it used to be initially.
