### ISSUE TITLE
Error adding new node to cluster: Node is invalid with 'spec.providerID' forbidden error

### ISSUE THREAD

**Issue by vadossam** [kubevirt/cloud-provider-kubevirt#226]
We encountered the following error when attempting to add a new node to a tenant cluster:
```
Node "xxx" is invalid: spec.providerID: Forbidden: node updates may not change providerID except from "" to valid, requeuing
```
Initially, we used another cloud provider to add nodes to the cluster. However, when we attempted to re-add them, we received the above error message. It appears that when updating the node manifest, the cloud-provider-kubevirt attempts to update the providerID field value with `providerID: kubevirt://nodeName`

Is it possible to disable updates to this field if it already exists?"

**Comment by mfranczy** [comment]
hey @vadossam, it's not possible to do so. The `providerID` field is used for VirtualMachine lookup. Looks like previously you had a different VM instance. I would suggest to initialize nodes again.

**Comment by mfranczy** [comment]
Feel free to re-open the issue if you have any questions.
