### ISSUE TITLE
Will there be a new cloud-provider-kubevirt release this year

### ISSUE THREAD

**Issue by sharath-srikanth-chellappa** [kubevirt/cloud-provider-kubevirt#266]
Hi Team, 

The last release for this repository is in the month of Oct 2022. Will there be a new release of cloud-provider-kubevirt in the near future ?

Is there a document that refers to the timelines for the release of this repository.

Thanks
Sharath

**Comment by mfranczy** [comment]
Hey, yes, there should be as we upgraded deps and bumped go version.
Also there are a few bugs I plan to fix before the release.
There is no document as release dates are quite flexible, on demand :)

@sharath-srikanth-chellappa do you have any special requirement?

**Comment by sharath-srikanth-chellappa** [comment]
So we were rebasing our fork of the repo on top of the latest release which is when we came across the fact that the last one was in October 2022.

Which is why we got curious as to when the next one would come in to have a better idea on the updates required on our end (whenever the new release comes in)

**Comment by mfranczy** [comment]
Definitely a new release will come this year.

**Comment by mfranczy** [comment]
New releases have been provided.
