### ISSUE TITLE
Support Local ExternalTrafficPolicy

### ISSUE THREAD

**Issue by hdurand0710** [kubevirt/cloud-provider-kubevirt#41]
As mentioned in this ticket: https://github.com/kubevirt/cloud-provider-kubevirt/issues/15, EnsureLoadBalancer can only support an `ExternalTrafficPolicy=Cluster`.
It would also require:
-  Do not label the proxy pod/VMI where actual pod does not exist
 - React on endpoint updates (if the actual pod is rescheduled on a different node)

Is there a plan to fix this issue to have `ExternalTrafficPolicy=Local` work ?
We for example have this ticket opened https://github.com/kubermatic/kubermatic/issues/9022 by our customer that would like to use the `Local` externalTrafficPolicy.

**Comment by gonzolino** [comment]
Hi @hdurand0710,
I agree that there is probably something wrong with the labelling of pods/VMIs.

However, there are currently no plans to fix this, since I do not have a proper dev environment available at the moment.
Of course, PRs fixing this are welcome :)

**Comment by moadqassem** [comment]
@gonzolino This might be a potential fix for the issue. https://github.com/kubermatic/cloud-provider-kubevirt/pull/4

**Comment by timstoop** [comment]
@mfranczy Are you still working on this? Anything anyone else can help with? This is a fairly important feature for us, so happy to provide assistance.

**Comment by mfranczy** [comment]
@timstoop currently I have no bandwidth for that. IMO there should be another controller that watches for endpoints in the tenant cluster and updates the endpoint in the infra cluster. If you're willing to contribute to that we can sync on CAPK upstream meeting.

**Comment by kvaps** [comment]
/reopen

fix is ready to review
https://github.com/kubevirt/cloud-provider-kubevirt/pull/330
