### ISSUE TITLE
Use distroless base image rather than alpine

### ISSUE THREAD

**Issue by inductor** [kubevirt/cloud-provider-kubevirt#50]
https://github.com/kubernetes/cloud-provider-gcp/blob/c2a51fc35cbf856dc4bab2a0d83ae46993ebe7f2/WORKSPACE#L78
https://github.com/kubernetes/cloud-provider-aws/blob/master/Dockerfile#L25
https://github.com/kubernetes/kubernetes/blob/7c46f40bdf89a437ecdbc01df45e235b5f6d9745/CHANGELOG/CHANGELOG-1.22.md#no-really-you-must-read-this-before-you-upgrade

Many of Kubernetes community folks decided to use Distroless as their base image. Alpine is a great distro but what about using Distroless? :)

**Comment by mfranczy** [comment]
we've decided to go with UBI image registry.redhat.io/ubi9/ubi-micro

/close
