### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by qinqon** [kubevirt/cloud-provider-kubevirt#92]
Add integration covering al the use cases, one solution would be to copy mechanism from capk.

**Comment by nirarg** [comment]
Those tests would be done using cluster-api clusters

For more info about cluster-api, see:

[cluster-api](https://github.com/kubernetes-sigs/cluster-api) github repository
[cluster-api-provider-kubevirt](https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt) repository
The cluster-api can be initiated using clusterctl cli ([quick start](https://cluster-api.sigs.k8s.io/user/quick-start.html))
kubevirt platform command: clusterctl init --infrastructure kubevirt
